if (!require("pacman")) install.packages("pacman")
pacman::p_load(Rcpp, RcppArmadillo, rmarkdown,mvtnorm,Matrix,MCMCpack,VGAM,stringr,plyr,pryr,dplyr,tidyr,purrr,tibble,lme4)

# library(Rcpp)
# library(rmarkdown)
# library(RcppArmadillo)
# library(mvtnorm)
# library(Matrix)
# library(MCMCpack)
# library(VGAM)
# library(stringr)
# library(plyr)
# library(pryr)
# library(dplyr)
# library(tidyr)
# library(purrr)
# library(tibble)
# library(lme4)
detach("package:plyr", unload=TRUE)

