---
title: ""
output: pdf_document
geometry: margin=3cm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE)
```
\pagenumbering{gobble}

```{r headerinfo, echo=FALSE,fig.height=1.2}
#library(plotrix)
par(mai=c(0,0.01,0.01,0.01))
plot(NA,ylim=c(0,7),xlim=c(0,10),xaxt="n",yaxt="n",ylab="",xlab="")
text(0,6,paste("Patient ID:",patient_name),pos=4)
text(0,5,paste("Patient initials:",Patient_Initials),pos=4)
text(0,4,paste("Clinician ID:",Clinician_ID),pos=4)
text(0,3,paste("Clinic name:",Clinic_Name),pos=4)
text(0,2,paste("Evaluation date: ",format(Sys.time(), "%A, %B %d, %Y"),sep=""),pos=4)
text(0,1,paste("Number of weeks in treatment:",WeeksInTreatment),pos=4)
#text(9,3,"Status:",pos=2)
#draw.circle(9.5,3,.5,col="Red")
#text(9.5,3,"Negative\nChange",cex=.8,col="white")
```


```{r noXaxisfigs, echo=FALSE, fig.height=1.5}
ShortLab2LongLab = function(x){
  if(x=="sleep_dur"){return("Sleep Duration\n(hours)")}
  if(x=="sleep_interr"){return("# of Sleep\nInterruptions")}
  if(x=="sleep_tosleep"){return("Time to sleep")}
  if(x=="stepcounts"){return("Step count")}
  if(x=="pause"){return("% Time\nStationary")}
  if(x=="gps_routine"){return("Routine")}
  if(x=="comm_time"){return("Minutes Spent\nTalking/Texting\nOn Phone")}
  if(x=="net_size"){return("Size of\nSocial Network")}
  if(x=="Hometime"){return("Time Spent At Home")}
  if(x=="ProbPause"){return("% Time\nStationary")}
  if(x=="CircdnRtn"){return("Routine")}
  if(x=="SigLocsVisited"){return("# of Significant Locations Visited")}
}
for(i in 1:(ncol(submat)-2)){
  vals = as.numeric(submat[,i+1])
  lab = as.character(names(submat[i+1]))
  avgval = mean(vals)
  lab_show=ShortLab2LongLab(lab)
  xlen=length(vals)
  par(mai=c(.3,1.3,.1,.8),mgp=c(3,.7,0))
  plot(1:xlen,vals,ylab=lab_show,xaxt="n",xlab="",yaxt="n",type="l",lwd=.5)
  lines(lowess(1:xlen,vals,f=1/5+8/xlen),lwd=2)
  axis(1,at=seq(1,xlen,7),labels=1:ceiling(xlen/7))
  axis(2,las=2)
  axis(4,las=2)
}

```

```{r yesXaxisfig, echo=FALSE, fig.height=2}
ShortLab2LongLab = function(x){
  if(x=="sleep_dur"){return("Sleep Duration\n(hours)")}
  if(x=="sleep_interr"){return("# of Sleep\nInterruptions")}
  if(x=="sleep_tosleep"){return("Time to sleep")}
  if(x=="stepcounts"){return("Step count")}
  if(x=="pause"){return("% Time\nStationary")}
  if(x=="gps_routine"){return("Routine")}
  if(x=="comm_time"){return("Minutes Spent\nTalking/Texting\nOn Phone")}
  if(x=="net_size"){return("Size of\nSocial Network")}
  if(x=="Hometime"){return("Time Spent\nAt Home")}
  if(x=="ProbPause"){return("% Time\nStationary")}
  if(x=="CircdnRtn"){return("Routine")}
  if(x=="SigLocsVisited"){return("# of Significant\nLocations Visited")}
}
for(i in (ncol(submat)-1):(ncol(submat)-1)){
  vals = as.numeric(submat[,i+1])
  lab = as.character(names(submat[i+1]))
  avgval = mean(vals)
  lab_show=ShortLab2LongLab(lab)
  xlen=length(vals)
  par(mai=c(.9,1.3,.1,.8),mgp=c(3,.7,0))
  plot(1:xlen,vals,ylab=lab_show,xaxt="n",xlab="Weeks since first session\n",yaxt="n",type="l",lwd=.5)
  lines(lowess(1:xlen,vals,f=1/5+8/xlen),lwd=2)
  axis(1,at=seq(1,xlen,7),labels=1:ceiling(xlen/7))
  axis(2,las=2)
  axis(4,las=2)
}

```





